"""empty message

Revision ID: b4398c82993e
Revises: 4e2ea6650398
Create Date: 2018-10-29 00:12:23.623296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4398c82993e'
down_revision = '4e2ea6650398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserData', sa.Column('device_id', sa.String(length=64), nullable=True))
    op.add_column('UserData', sa.Column('device_nickname', sa.String(length=10), nullable=True))
    op.add_column('UserData', sa.Column('line_nickname', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserData', 'line_nickname')
    op.drop_column('UserData', 'device_nickname')
    op.drop_column('UserData', 'device_id')
    # ### end Alembic commands ###
